# Generated by Django 4.2.7 on 2023-12-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_task_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='descriptions',
        ),
    ]
