# Generated by Django 4.2.7 on 2023-11-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('tier_1', 'Can view own tasks and tasks project'), ('tier_2', 'Can view all tasks and projects, can create projects and tasks in own projects'), ('tier_3(Admin)', 'Can view, create and edit all tasks and projects'))},
        ),
    ]
