    # Generated by Django 4.2.3 on 2023-12-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('tier_1', 'Пользователь может видеть свои задачи и проекты, в которых есть его задачи.'), ('tier_2', 'Пользователь может видеть все задачи и все проекты. Может создавать проекты и задачив своих проектах.'), ('tier_3(Admin)', 'Может видеть все проекты и задачи. Может создавать проекты и задачи во всех проектах'))},
        ),
    ]
